spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/kodilla_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: kodilla_user
    password: kodilla_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: your-very-secure-and-long-secret-key-12345